/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      fontFamily: {
        syne: ['Syne', 'sans-serif'],
        mono: ['Space Mono', 'monospace'],
      },
      colors: {
        x: '#ff6b6b',
        o: '#4ecdc4',
        accent: '#f7c948',
        bg: '#0a0a0f',
        surf: '#12121a',
        surf2: '#1a1a28',
      },
      keyframes: {
        logoIn:    { from: { opacity: '0', transform: 'translateY(-28px) scale(0.82)' }, to: { opacity: '1', transform: 'none' } },
        fadeUp:    { from: { opacity: '0', transform: 'translateY(18px)' },              to: { opacity: '1', transform: 'none' } },
        screenIn:  { from: { opacity: '0', transform: 'scale(0.97) translateY(7px)' },  to: { opacity: '1', transform: 'none' } },
        floatP:    { '0%':  { transform: 'translateY(105vh) scale(0)',  opacity: '0'    },
                     '8%':  { opacity: '0.55' },
                     '88%': { opacity: '0.22' },
                     '100%':{ transform: 'translateY(-8vh) scale(1)',   opacity: '0'    } },
        confetti:  { '0%':  { transform: 'translateY(0) rotate(0)',          opacity: '1' },
                     '80%': { opacity: '1' },
                     '100%':{ transform: 'translateY(108vh) rotate(720deg)', opacity: '0' } },
        placeMark: { '0%':  { transform: 'scale(0) rotate(-14deg)', opacity: '0'    },
                     '62%': { transform: 'scale(1.18) rotate(4deg)'                 },
                     '100%':{ transform: 'scale(1) rotate(0)',       opacity: '1'    } },
        winPulse:  { '0%':  { transform: 'scale(1)'    },
                     '30%': { transform: 'scale(1.13)' },
                     '62%': { transform: 'scale(0.97)' },
                     '100%':{ transform: 'scale(1.06)' } },
        bounceWin: { '0%':  { transform: 'translateY(0) scale(1)'          },
                     '28%': { transform: 'translateY(-11px) scale(1.07)'   },
                     '62%': { transform: 'translateY(3px) scale(0.98)'     },
                     '100%':{ transform: 'translateY(0) scale(1)'          } },
        pulseDot:  { '0%,100%': { transform: 'scale(1)',    opacity: '1'   },
                     '50%':     { transform: 'scale(1.35)', opacity: '0.6' } },
        musicBar:  { from: { height: '4px' }, to: { height: '13px' } },
      },
      animation: {
        'logo-in':    'logoIn 0.8s cubic-bezier(0.34,1.56,0.64,1) both',
        'fade-up':    'fadeUp 0.6s ease both',
        'screen-in':  'screenIn 0.38s cubic-bezier(0.4,0,0.2,1) both',
        'float-p':    'floatP linear infinite',
        'confetti':   'confetti linear forwards',
        'place-mark': 'placeMark 0.34s cubic-bezier(0.34,1.56,0.64,1)',
        'win-pulse':  'winPulse 0.7s ease forwards',
        'bounce-win': 'bounceWin 0.6s cubic-bezier(0.34,1.56,0.64,1)',
        'pulse-dot':  'pulseDot 1.5s ease-in-out infinite',
        'music-bar':  'musicBar 0.7s ease-in-out infinite alternate',
      },
    },
  },
  plugins: [],
}
